baseURL: https://changxiawushi.github.io/
# Test locally
# baseURL: http://localhost:1313
# languageCode: zh-CN
title: 长夏无事
theme: "PaperMod"

paginate: 5
enableEmoji: true

# defaultContentLanguage: zh-CN
# languages:
#     zh-CN:
#       languageName: 中文
menu:
  main:
    - name: 标签
      url: tags/
      weight: 1
    - name: RSS订阅
      url: index.xml
      weight: 2
    # - name: 搜索
    #   url: search/
    - name: 文章
      url: posts/
      weight: 3

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  env: production
  defaultTheme: auto
  ShowReadingTime: true
  disableSpecial1stPost: true
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowRssButtonInSectionTermList: true
  ShowToc: true
  comments: true